name: Dependency Updates

on:
  schedule:
    - cron: '0 0 * * 1'  # Run every Monday at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  dependency-updates:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Check for outdated dependencies
        id: outdated
        run: |
          OUTDATED=$(npm outdated --json || true)
          if [ "$OUTDATED" == "{}" ] || [ -z "$OUTDATED" ]; then
            echo "No outdated dependencies found."
            echo "has_updates=false" >> $GITHUB_OUTPUT
          else
            echo "Outdated dependencies found:"
            echo "$OUTDATED" | jq '.'
            echo "has_updates=true" >> $GITHUB_OUTPUT
            echo "updates<<EOF" >> $GITHUB_OUTPUT
            echo "$OUTDATED" | jq -r 'to_entries | .[] | "\(.key): \(.value.current) -> \(.value.latest)"' >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi
      
      - name: Create issue for dependency updates
        if: steps.outdated.outputs.has_updates == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const updates = `${{ steps.outdated.outputs.updates }}`;
            const updatesList = updates.split('\n').map(line => `- ${line}`).join('\n');
            
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '📦 Dependency Updates Available',
              body: `## Dependency Updates Available

The following dependencies have updates available:

${updatesList}

### Automated Update Instructions
1. Review the changes for breaking changes
2. Run \`npm update\` to update within semver ranges
3. For major version updates, update them individually with \`npm install package@latest\`
4. Test thoroughly after updates

This issue was automatically generated by the Dependency Updates workflow.
`,
              labels: ['dependencies', 'automated-issue']
            });