name: Continuous Integration

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]
  workflow_dispatch:

jobs:
  check-project-structure:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Check project structure
        id: check_structure
        run: |
          echo "Project Structure Check:"
          echo "======================="
          
          # Check for package.json
          if [ -f "package.json" ]; then
            echo "✅ package.json found"
            echo "package_json_exists=true" >> $GITHUB_OUTPUT
          else
            echo "⚠️ package.json not found in root directory"
            echo "package_json_exists=false" >> $GITHUB_OUTPUT
            
            # Check possible locations
            if find . -type f -name "package.json" | grep -q .; then
              echo "Found package.json files in other directories:"
              find . -type f -name "package.json" | sort
            fi
          fi
          
          # Check for key directories
          for dir in "client" "server" "electron" "shared"; do
            if [ -d "$dir" ]; then
              echo "✅ $dir directory found"
            else
              echo "ℹ️ $dir directory not found"
            fi
          done
          
          # Output the directory structure for reference
          echo -e "\nDirectory Structure:"
          find . -type d -not -path "*/node_modules/*" -not -path "*/\.*" | sort
    
    outputs:
      package_json_exists: ${{ steps.check_structure.outputs.package_json_exists }}
  
  lint-and-type-check:
    runs-on: ubuntu-latest
    needs: check-project-structure
    if: needs.check-project-structure.outputs.package_json_exists == 'true'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Type check
        run: |
          if grep -q "\"check\"" package.json; then
            npm run check
          else
            echo "No check script found in package.json, skipping"
          fi
        continue-on-error: true  # Don't fail the build for type errors during development
  
  build:
    runs-on: ubuntu-latest
    needs: check-project-structure
    if: needs.check-project-structure.outputs.package_json_exists == 'true'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build web app
        run: |
          if grep -q "\"build\"" package.json; then
            npm run build
          else
            echo "No build script found in package.json, skipping"
          fi
      
      - name: Test build for secrets
        run: |
          if [ -f "./build-resources/clean-secrets.js" ]; then
            node ./build-resources/clean-secrets.js
          else
            echo "clean-secrets.js not found, skipping"
          fi
      
      - name: Upload build artifacts (if exists)
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: |
            build/
            dist/
          if-no-files-found: ignore
          retention-days: 7